OBJS := # FILL: objects in current folder
DIRS := utils MAIN_UNIT # FILL: subdirs contain src files

# NOTE: here should be SUB_MAKE_INCLUDE, different from the top Makefile
include $(SUB_MAKE_INCLUDE)